In [1]:
import pandas as pd
from datetime import datetime
import numpy as np

In [2]:
import py_vollib.black_scholes_merton.implied_volatility
import py_vollib_vectorized

In [3]:
df = pd.read_csv("final_processed_data.csv",parse_dates=True)

In [4]:
df.columns

Index(['INSTRUMENT', 'SYMBOL', 'EXPIRY_DT', 'STRIKE_PR', 'OPTION_TYP',
       'OPEN_x', 'HIGH_x', 'LOW_x', 'CLOSE_x', 'SETTLE_PR', 'CONTRACTS',
       'VAL_INLAKH', 'OPEN_INT', 'CHG_IN_OI', 'TIMESTAMP', 'OPEN_y', 'HIGH_y',
       'LOW_y', 'CLOSE_y', 'TOTTRDQTY', 'DELIVERABLE', 'DAYS_TO_EXP'],
      dtype='object')

In [5]:
df['TIMESTAMP']= pd.to_datetime(df['TIMESTAMP'])
df['EXPIRY_DT']= pd.to_datetime(df['EXPIRY_DT'])

In [6]:
df['DAYS_TO_EXP']=df['EXPIRY_DT']-df['TIMESTAMP']

In [7]:
df.dtypes

INSTRUMENT              object
SYMBOL                  object
EXPIRY_DT       datetime64[ns]
STRIKE_PR              float64
OPTION_TYP              object
OPEN_x                 float64
HIGH_x                 float64
LOW_x                  float64
CLOSE_x                float64
SETTLE_PR              float64
CONTRACTS              float64
VAL_INLAKH             float64
OPEN_INT               float64
CHG_IN_OI              float64
TIMESTAMP       datetime64[ns]
OPEN_y                 float64
HIGH_y                 float64
LOW_y                  float64
CLOSE_y                float64
TOTTRDQTY                int64
DELIVERABLE              int64
DAYS_TO_EXP    timedelta64[ns]
dtype: object

In [8]:
df.loc[:,'OPTION_TYP'] = df['OPTION_TYP'].str.slice(0,1)

In [9]:
df.loc[:,'OPTION_TYP'] = df['OPTION_TYP'].str.lower()

In [10]:
df1=df[:15]

In [11]:
df1

,INSTRUMENT,SYMBOL,EXPIRY_DT,STRIKE_PR,OPTION_TYP,OPEN_x,HIGH_x,LOW_x,CLOSE_x,SETTLE_PR,...,OPEN_INT,CHG_IN_OI,TIMESTAMP,OPEN_y,HIGH_y,LOW_y,CLOSE_y,TOTTRDQTY,DELIVERABLE,DAYS_TO_EXP
0,OPTSTK,ACC,2019-04-25,1140.0,c,0.0,0.0,0.0,307.30,512.65,...,0.0,0.0,2019-04-01,1673.0,1723.4,1637.65,1646.9,1576508,464755,24 days
1,OPTSTK,ACC,2019-04-25,1160.0,c,0.0,0.0,0.0,289.00,492.75,...,0.0,0.0,2019-04-01,1673.0,1723.4,1637.65,1646.9,1576508,464755,24 days
2,OPTSTK,ACC,2019-04-25,1180.0,c,0.0,0.0,0.0,271.05,472.85,...,0.0,0.0,2019-04-01,1673.0,1723.4,1637.65,1646.9,1576508,464755,24 days
3,OPTSTK,ACC,2019-04-25,1200.0,c,0.0,0.0,0.0,253.45,452.95,...,0.0,0.0,2019-04-01,1673.0,1723.4,1637.65,1646.9,1576508,464755,24 days
4,OPTSTK,ACC,2019-04-25,1220.0,c,0.0,0.0,0.0,236.30,433.05,...,0.0,0.0,2019-04-01,1673.0,1723.4,1637.65,1646.9,1576508,464755,24 days
5,OPTSTK,ACC,2019-04-25,1240.0,c,0.0,0.0,0.0,219.60,413.15,...,0.0,0.0,2019-04-01,1673.0,1723.4,1637.65,1646.9,1576508,464755,24 days
6,OPTSTK,ACC,2019-04-25,1260.0,c,0.0,0.0,0.0,203.45,393.25,...,0.0,0.0,2019-04-01,1673.0,1723.4,1637.65,1646.9,1576508,464755,24 days
7,OPTSTK,ACC,2019-04-25,1280.0,c,0.0,0.0,0.0,187.90,373.35,...,0.0,0.0,2019-04-01,1673.0,1723.4,1637.65,1646.9,1576508,464755,24 days
8,OPTSTK,ACC,2019-04-25,1300.0,c,0.0,0.0,0.0,173.00,353.45,...,0.0,0.0,2019-04-01,1673.0,1723.4,1637.65,1646.9,1576508,464755,24 days
9,OPTSTK,ACC,2019-04-25,1320.0,c,0.0,0.0,0.0,158.65,333.60,...,0.0,0.0,2019-04-01,1673.0,1723.4,1637.65,1646.9,1576508,464755,24 days
10,OPTSTK,ACC,2019-04-25,1340.0,c,0.0,0.0,0.0,145.00,313.80,...,0.0,0.0,2019-04-01,1673.0,1723.4,1637.65,1646.9,1576508,464755,24 days
11,OPTSTK,ACC,2019-04-25,1360.0,c,0.0,0.0,0.0,132.10,294.00,...,0.0,0.0,2019-04-01,1673.0,1723.4,1637.65,1646.9,1576508,464755,24 days
12,OPTSTK,ACC,2019-04-25,1380.0,c,0.0,0.0,0.0,119.90,274.30,...,0.0,0.0,2019-04-01,1673.0,1723.4,1637.65,1646.9,1576508,464755,24 days
13,OPTSTK,ACC,2019-04-25,1400.0,c,0.0,0.0,0.0,200.00,254.70,...,800.0,0.0,2019-04-01,1673.0,1723.4,1637.65,1646.9,1576508,464755,24 days
14,OPTSTK,ACC,2019-04-25,1420.0,c,0.0,0.0,0.0,97.85,235.30,...,0.0,0.0,2019-04-01,1673.0,1723.4,1637.65,1646.9,1576508,464755,24 days

In [12]:
r = 0.05

In [13]:
df1['IV'] = py_vollib_vectorized.vectorized_implied_volatility_black(df1['SETTLE_PR'],df1['CLOSE_y'],df1['STRIKE_PR'],df1['DAYS_TO_EXP']/np.timedelta64(1, 'D')/365,r,df1['OPTION_TYP'],q=0,model='black_scholes_merton')

<ipython-input-13-d4b249c8e832>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['IV'] = py_vollib_vectorized.vectorized_implied_volatility_black(df1['SETTLE_PR'],df1['CLOSE_y'],df1['STRIKE_PR'],df1['DAYS_TO_EXP']/np.timedelta64(1, 'D')/365,r,df1['OPTION_TYP'],q=0,model='black_scholes_merton')

In [14]:
df1['IV']

0     1.032690
1     0.993075
2     0.953933
3     0.915233
4     0.876946
5     0.839042
6     0.801490
7     0.764260
8     0.727321
9     0.691705
10    0.657243
11    0.622788
12    0.590146
13    0.558975
14    0.530540
Name: IV, dtype: float64

In [16]:
df1['DELTA'] = py_vollib_vectorized.vectorized_delta(df1['OPTION_TYP'],df1['CLOSE_y'],df1['STRIKE_PR'],df1['DAYS_TO_EXP']/np.timedelta64(1, 'D')/365,r,df1['IV'],model='black_scholes')

<ipython-input-16-741dc4890a33>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['DELTA'] = py_vollib_vectorized.vectorized_delta(df1['OPTION_TYP'],df1['CLOSE_y'],df1['STRIKE_PR'],df1['DAYS_TO_EXP']/np.timedelta64(1, 'D')/365,r,df1['IV'],model='black_scholes')

In [17]:
df1['DELTA']

0     0.937486
1     0.935309
2     0.933017
3     0.930599
4     0.928041
5     0.925328
6     0.922443
7     0.919366
8     0.916071
9     0.912241
10    0.907816
11    0.903030
12    0.897206
13    0.890234
14    0.881362
Name: DELTA, dtype: float64